project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - files/cv_elshan_garashli_unigraz.pdf

website:
  title: "Elshan Garashli"
  site-url: "https://elshangarashli.com"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: files/cv_elshan_garashli_unigraz.pdf
  page-footer:
    left: "Elshan Garashli"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

